# Generated by Django 2.2.3 on 2019-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_estudiante_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
