# Generated by Django 2.2.3 on 2019-08-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20190814_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='precio',
            field=models.FloatField(default=1),
        ),
    ]
